<a href="https://colab.research.google.com/github/Ravikanth45/appllab/blob/colab-appl/APP(numpy).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

## **0 dimensional array**

In [ ]:
b=np.array(534)
print(b)

534


In [ ]:
b=np.array(5343)
print(b)

5343


In [ ]:
b=np.array(200)
print(b)

200


# **1-DIMENSION ARRAY**


**collection of 0 elements is from 1-dimension**

In [ ]:
c=np.array([200,300])
print(c)

[200 300]


In [ ]:
c=np.array([5787,57])
print(c)

[5787   57]


In [ ]:
c=np.array([245,145])
print(c)

[245 145]


In [ ]:
c=np.array([454,245])
print(c)

[454 245]


# **2 dimensional array**

In [ ]:
d=np.array([[200,300],[400,500]])
print(d)

[[200 300]
 [400 500]]


In [ ]:
d=np.array([[578,5784],[574,548]])
print(d)

[[ 578 5784]
 [ 574  548]]


In [ ]:
d=np.array([[200,300],[25485,545]])
print(d)

[[  200   300]
 [25485   545]]


In [ ]:
d=np.array([[5746,58786],[8657,215374]])
print(d)

[[  5746  58786]
 [  8657 215374]]


# **3 dimensional array**

In [ ]:
e=np.array([[[200,300],[400,500]],[[600,700],[800,900]]])
print(e)

[[[200 300]
  [400 500]]

 [[600 700]
  [800 900]]]


In [ ]:
e=np.array([[[200,300],[400,500]],[[600,700],[800,900]]])
print(e)

[[[200 300]
  [400 500]]

 [[600 700]
  [800 900]]]


In [ ]:
e=np.array([[[200,300],[400,500]],[[600,700],[800,900]]])
print(e)

[[[200 300]
  [400 500]]

 [[600 700]
  [800 900]]]


In [ ]:
e=np.array([[[266,300],[5485,54787]],[[546,8646],[454,454]]])
print(e)

[[[  266   300]
  [ 5485 54787]]

 [[  546  8646]
  [  454   454]]]


#**NDMIN**

In [ ]:
arr=np.array([1,2,3,4],ndmin=3)
print(arr)
print(arr.ndim)

[[[1 2 3 4]]]
3


In [ ]:
arr=np.array([1,2,3,4],ndmin=2)
print(arr)
print(arr.ndim)

[[1 2 3 4]]
2


In [ ]:
arr=np.array([8,4,85,4],ndmin=3)
print(arr)
print(arr.ndim)

[[[ 8  4 85  4]]]
3


In [ ]:
arr=np.array([748,8578,5,54],ndmin=3)
print(arr)
print(arr.ndim)

[[[ 748 8578    5   54]]]
3


#**ARRAY**

In [ ]:
arr=np.array([1,2,3,4,5,6,8])
print(arr[1])
print(arr[3]+arr[4])

2
9


#**2D array**


In [ ]:
arr=np.array([[1,2,3,4],[5,6,7,8,9]])
print(arr[0],[1])

[1, 2, 3, 4] [1]


<ipython-input-23-ec2f9e724333>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr=np.array([[1,2,3,4],[5,6,7,8,9]])


#**3D array**

In [ ]:
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr[0,1,2])
print(arr[0,0,1])

6
2


#**NEGATIVE INDEXING**

In [ ]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,-1])

10


#**ARRAY DATASETS**

In [ ]:
arr=np.array([1,2,3])
print(arr.dtype)

int64


#**converting datatype**

In [ ]:
arr=np.array([1.1,2.1,3.1])
newar=arr.astype('i')
print(newar)

[1 2 3]


# **asarray()**

**row major order("C")**

**column major order("F")**

**occured in 2-Dimension array**

In [ ]:
a=([200,300],[400,500])
b=np.asarray(a,order='c')
print(d)

[[  5746  58786]
 [  8657 215374]]


In [ ]:
for i in np.nditer(d):
  print(i)

5746
58786
8657
215374


In [ ]:
x=([200,300],[400,500])
y=np.asarray(a,order='F')
print(y)

[[200 300]
 [400 500]]


In [ ]:
for i in np.nditer(y):
  print(i)

200
400
300
500


# **frombuffer()**

#converts the string into bufffer
#using b before the string

In [ ]:
import numpy as np

In [ ]:
Y=b'First year IT'
np.frombuffer(Y,dtype='S1')

array([b'F', b'i', b'r', b's', b't', b' ', b'y', b'e', b'a', b'r', b' ',
       b'I', b'T'], dtype='|S1')

In [ ]:
np.frombuffer(Y,dtype='S1',count=3)

array([b'F', b'i', b'r'], dtype='|S1')

In [ ]:
np.frombuffer(Y,dtype='S1',offset=8)

array([b'a', b'r', b' ', b'I', b'T'], dtype='|S1')

In [ ]:
np.frombuffer(Y,dtype='S1',count=2,offset=8)

array([b'a', b'r'], dtype='|S1')

# **fromiter()**

In [ ]:
a=[100,200,300,400,500,600,700,800,900,1000]
np.fromiter(a,dtype='S1',count=4)

array([b'1', b'2', b'3', b'4'], dtype='|S1')

In [ ]:
a=[100,200,300,400,500,600,700,800,900,1000]
np.fromiter(a,dtype='S1')

array([b'1', b'2', b'3', b'4', b'5', b'6', b'7', b'8', b'9', b'1'],
      dtype='|S1')

# **zeros()**

In [ ]:
a=np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
a=np.zeros((5,4,4))
print(a)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [ ]:
a=np.full((4,5),8)
print(a)

[[8 8 8 8 8]
 [8 8 8 8 8]
 [8 8 8 8 8]
 [8 8 8 8 8]]


In [ ]:
a=np.full((4,5,6),7)
print(a)

[[[7 7 7 7 7 7]
  [7 7 7 7 7 7]
  [7 7 7 7 7 7]
  [7 7 7 7 7 7]
  [7 7 7 7 7 7]]

 [[7 7 7 7 7 7]
  [7 7 7 7 7 7]
  [7 7 7 7 7 7]
  [7 7 7 7 7 7]
  [7 7 7 7 7 7]]

 [[7 7 7 7 7 7]
  [7 7 7 7 7 7]
  [7 7 7 7 7 7]
  [7 7 7 7 7 7]
  [7 7 7 7 7 7]]

 [[7 7 7 7 7 7]
  [7 7 7 7 7 7]
  [7 7 7 7 7 7]
  [7 7 7 7 7 7]
  [7 7 7 7 7 7]]]


#**full()**

In [ ]:
import numpy as np
a=np.full([4,6],8)
print(a)

[[8 8 8 8 8 8]
 [8 8 8 8 8 8]
 [8 8 8 8 8 8]
 [8 8 8 8 8 8]]


In [ ]:
a=np.full([3,4,6],8)
print(a)

[[[8 8 8 8 8 8]
  [8 8 8 8 8 8]
  [8 8 8 8 8 8]
  [8 8 8 8 8 8]]

 [[8 8 8 8 8 8]
  [8 8 8 8 8 8]
  [8 8 8 8 8 8]
  [8 8 8 8 8 8]]

 [[8 8 8 8 8 8]
  [8 8 8 8 8 8]
  [8 8 8 8 8 8]
  [8 8 8 8 8 8]]]


# **random.rand()**

In [ ]:
a=np.random.rand(5,6)
print(a)

[[0.64357107 0.97674026 0.81545145 0.88384202 0.52196139 0.72211047]
 [0.24632752 0.03780398 0.93520633 0.56762675 0.49798931 0.29254688]
 [0.75672071 0.40958449 0.1438567  0.10930141 0.41131492 0.25206085]
 [0.07455182 0.84454543 0.09956812 0.98327067 0.25459967 0.23903152]
 [0.98453456 0.41945223 0.80910967 0.88078148 0.11338572 0.10857274]]


In [ ]:
a=np.random.rand(4,5,6)
print(a)

[[[0.25879192 0.3420824  0.11997295 0.52120781 0.82937126 0.59708442]
  [0.25555326 0.93066564 0.03441486 0.77701708 0.29719305 0.58668604]
  [0.95317024 0.71828818 0.38139367 0.96413361 0.84666817 0.24494268]
  [0.46261049 0.67844012 0.67768198 0.91664331 0.09368791 0.638256  ]
  [0.56130044 0.65694573 0.21077647 0.09529608 0.31432292 0.10918611]]

 [[0.98177169 0.20786693 0.86792406 0.38477791 0.77015719 0.39467783]
  [0.18492496 0.5242234  0.73367315 0.47933817 0.04089252 0.49410298]
  [0.45461694 0.2099495  0.91522212 0.4465204  0.49016542 0.88542101]
  [0.62452222 0.95723894 0.62864579 0.21790434 0.36358222 0.50987311]
  [0.48513283 0.81415785 0.58976752 0.79425951 0.36403467 0.3403406 ]]

 [[0.12107338 0.83027849 0.56224505 0.53659497 0.50261359 0.86586594]
  [0.26488421 0.72148081 0.90530357 0.36299345 0.31777207 0.08989863]
  [0.28882046 0.39813566 0.71427688 0.21104153 0.75244245 0.55462738]
  [0.40598676 0.05745002 0.3757696  0.20122472 0.07428755 0.62885087]
  [0.17632061 0.

In [ ]:
a=np.random.rand(5,7,2)
print(a)

[[[0.87862555 0.01777944]
  [0.32752415 0.35966189]
  [0.51879753 0.50527111]
  [0.06911798 0.16215413]
  [0.50516479 0.35151878]
  [0.61695219 0.04550162]
  [0.75689086 0.57262917]]

 [[0.87487157 0.63176393]
  [0.69955045 0.83391173]
  [0.40244692 0.0939491 ]
  [0.38715052 0.62006238]
  [0.36011818 0.87614313]
  [0.34730553 0.75397571]
  [0.54976934 0.8047495 ]]

 [[0.511058   0.12410862]
  [0.99694727 0.83202348]
  [0.73178065 0.91296968]
  [0.32624329 0.49766374]
  [0.72237177 0.31192983]
  [0.31447559 0.32038742]
  [0.93267583 0.72754915]]

 [[0.24943912 0.25052514]
  [0.56830882 0.25550878]
  [0.91286223 0.89628238]
  [0.93858387 0.6722669 ]
  [0.85639572 0.09830451]
  [0.18170121 0.14155334]
  [0.12775274 0.98912767]]

 [[0.52153088 0.92759464]
  [0.96725696 0.94366201]
  [0.28663783 0.1399273 ]
  [0.71688673 0.83163358]
  [0.44250409 0.45372426]
  [0.9506873  0.67771413]
  [0.02811237 0.80470119]]]


# **ones()**

same as zero

In [ ]:
import numpy as np

In [ ]:
a=np.ones([4,6], dtype = int)
print(a)

[[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]]


In [ ]:
a=np.ones([5,8], dtype = int)
print(a)

[[1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]]


#**eye()**

**diagonal elements are 1 remain are 0**

In [ ]:
a=np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
a=np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
a=np.eye(8)
print(a)

[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]


#**arange()**

In [ ]:
a=np.arange (30,50,2)
print(a)

[30 32 34 36 38 40 42 44 46 48]


In [ ]:
a=np.arange (30,20,2)
print(a)

[]


In [ ]:
a=np.arange (30,40,6)
print(a)

[30 36]


In [ ]:
a=np.arange (30,60,3,dtype = float)
print(a)

[30. 33. 36. 39. 42. 45. 48. 51. 54. 57.]


# **Reshape()**

In [ ]:
d = a.reshape(5,2)
d

array([[30., 33.],
       [36., 39.],
       [42., 45.],
       [48., 51.],
       [54., 57.]])

#**line space()**

In [ ]:
a=np.linspace(10,100,10)
print(a)

[ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]


In [ ]:
a=np.linspace (10,100,10,endpoint=False)
print(a)

[10. 19. 28. 37. 46. 55. 64. 73. 82. 91.]


In [ ]:
a=np.linspace(10,100,10,endpoint=False)
print(a)

[10. 19. 28. 37. 46. 55. 64. 73. 82. 91.]


#**logspace()**

In [ ]:
a=np.logspace(1,10,10,base=3,dtype=int)
print(a)

[    3     9    27    81   243   729  2187  6561 19683 59049]


In [ ]:
a=np.logspace(1,10,10,dtype=int)
print(a)

[         10         100        1000       10000      100000     1000000
    10000000   100000000  1000000000 10000000000]


#**ARRAY PROPERTIES**

SIZE -***np.size(array)***

SHAPE- ***np.shape(array)***

DTYPE -***a.dtype***

In [ ]:
a = np.arange(10,100,10)
a

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
a = a.reshape(3,3)
a

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [ ]:
np.size(a)

9

In [ ]:
a.dtype

dtype('int64')

In [ ]:
b =  np.array([10,20,30],dtype=float)
print(b)

[10. 20. 30.]


In [ ]:
b.dtype

dtype('float64')

#**ARRAY OPERATIONS**

***Accesing the elemnts***

***Slicing*** -*****means extracting some pertion of data*****

*Acessing and slicing operations
concentenate()
copy()                                          stack()*






##**Accessing And Slicing Operations**

In [ ]:
a=np.array([[234,387,465,834,964,201],[543,500,823,645,723,923]])

In [ ]:
print(a)

[[234 387 465 834 964 201]
 [543 500 823 645 723 923]]


In [ ]:
a[0]

array([234, 387, 465, 834, 964, 201])

In [ ]:
a[1]

array([543, 500, 823, 645, 723, 923])

In [ ]:
a[1][1]

500

In [ ]:
a[1][4]

723

In [ ]:
h=np.arange(10,200,10)
print(h)

[ 10  20  30  40  50  60  70  80  90 100 110 120 130 140 150 160 170 180
 190]


In [ ]:
h[5:16]

array([ 60,  70,  80,  90, 100, 110, 120, 130, 140, 150, 160])

In [ ]:
h=np.arange(10,3000,10)
print(h)

[  10   20   30   40   50   60   70   80   90  100  110  120  130  140
  150  160  170  180  190  200  210  220  230  240  250  260  270  280
  290  300  310  320  330  340  350  360  370  380  390  400  410  420
  430  440  450  460  470  480  490  500  510  520  530  540  550  560
  570  580  590  600  610  620  630  640  650  660  670  680  690  700
  710  720  730  740  750  760  770  780  790  800  810  820  830  840
  850  860  870  880  890  900  910  920  930  940  950  960  970  980
  990 1000 1010 1020 1030 1040 1050 1060 1070 1080 1090 1100 1110 1120
 1130 1140 1150 1160 1170 1180 1190 1200 1210 1220 1230 1240 1250 1260
 1270 1280 1290 1300 1310 1320 1330 1340 1350 1360 1370 1380 1390 1400
 1410 1420 1430 1440 1450 1460 1470 1480 1490 1500 1510 1520 1530 1540
 1550 1560 1570 1580 1590 1600 1610 1620 1630 1640 1650 1660 1670 1680
 1690 1700 1710 1720 1730 1740 1750 1760 1770 1780 1790 1800 1810 1820
 1830 1840 1850 1860 1870 1880 1890 1900 1910 1920 1930 1940 1950 1960
 1970 

In [ ]:
h[123:212]

array([1240, 1250, 1260, 1270, 1280, 1290, 1300, 1310, 1320, 1330, 1340,
       1350, 1360, 1370, 1380, 1390, 1400, 1410, 1420, 1430, 1440, 1450,
       1460, 1470, 1480, 1490, 1500, 1510, 1520, 1530, 1540, 1550, 1560,
       1570, 1580, 1590, 1600, 1610, 1620, 1630, 1640, 1650, 1660, 1670,
       1680, 1690, 1700, 1710, 1720, 1730, 1740, 1750, 1760, 1770, 1780,
       1790, 1800, 1810, 1820, 1830, 1840, 1850, 1860, 1870, 1880, 1890,
       1900, 1910, 1920, 1930, 1940, 1950, 1960, 1970, 1980, 1990, 2000,
       2010, 2020, 2030, 2040, 2050, 2060, 2070, 2080, 2090, 2100, 2110,
       2120])

##**copy()**

***copying one array elements into another array***

In [ ]:
a=np.array([[234,387,465,834,964,201],[543,500,823,645,823,923]])
print(a)

[[234 387 465 834 964 201]
 [543 500 823 645 823 923]]


In [ ]:
b=np.array([[364,296,975,345,253,785],[241,940,823,764,241,623]])
print(b)

[[364 296 975 345 253 785]
 [241 940 823 764 241 623]]


In [ ]:
b=np.copy(a)
print(b)

[[234 387 465 834 964 201]
 [543 500 823 645 823 923]]


In [ ]:
a=np.copy(b)
print(a)

[[234 387 465 834 964 201]
 [543 500 823 645 823 923]]


In [ ]:
a,b

(array([[234, 387, 465, 834, 964, 201],
        [543, 500, 823, 645, 823, 923]]),
 array([[234, 387, 465, 834, 964, 201],
        [543, 500, 823, 645, 823, 923]]))

##**view**

***similar to copy but its acts like a refernace***

In [ ]:
c = b.view()
c

array([[234, 387, 465, 834, 964, 201],
       [543, 500, 823, 645, 823, 923]])

In [ ]:
print("a=",a)
print("b=",b)
print("c=",c)

a= [[234 387 465 834 964 201]
 [543 500 823 645 823 923]]
b= [[234 387 465 834 964 201]
 [543 500 823 645 823 923]]
c= [[234 387 465 834 964 201]
 [543 500 823 645 823 923]]


In [ ]:
a[1][2]=777
a

array([[234, 387, 465, 834, 964, 201],
       [543, 500, 777, 645, 823, 923]])

In [ ]:
b

array([[234, 387, 465, 834, 964, 201],
       [543, 500, 823, 645, 823, 923]])

In [ ]:
c

array([[234, 387, 465, 834, 964, 201],
       [543, 500, 823, 645, 823, 923]])

In [ ]:
b[0][4]=999
b

array([[234, 387, 465, 834, 999, 201],
       [543, 500, 823, 645, 823, 923]])

In [ ]:
c

array([[234, 387, 465, 834, 999, 201],
       [543, 500, 823, 645, 823, 923]])

##**sort()**

*sorting of elements*

In [ ]:
a = np.array([4325,3548,1911,8912,9012,3219,4358,8230])
print(a)

[4325 3548 1911 8912 9012 3219 4358 8230]


In [ ]:
np.sort(a)

array([1911, 3219, 3548, 4325, 4358, 8230, 8912, 9012])

In [ ]:
a=a.reshape(4,2)
print(a)

[[4325 3548]
 [1911 8912]
 [9012 3219]
 [4358 8230]]


In [ ]:
a=a.reshape(2,4)
print(a)

[[4325 3548 1911 8912]
 [9012 3219 4358 8230]]


In [ ]:
a=a.reshape(1,8)
print(a)

[[4325 3548 1911 8912 9012 3219 4358 8230]]


In [ ]:
a=a.reshape(8,1)
print(a)

[[4325]
 [3548]
 [1911]
 [8912]
 [9012]
 [3219]
 [4358]
 [8230]]


#**Based on Axis maximun functions implemented**

*Axis : 0 means column wise operations*


*Axis : 1 means row wise operations*

In [ ]:
a = np.array([[234,687,465,834,964,901],[543,500,823,645,823,723]])
print(a)

[[234 687 465 834 964 901]
 [543 500 823 645 823 723]]


In [ ]:
np.sort(a,axis=0) #column wise operations are sorted

array([[234, 500, 465, 645, 823, 723],
       [543, 687, 823, 834, 964, 901]])

In [ ]:
np.sort(a,axis=1) #row wise operations are sorted

array([[234, 465, 687, 834, 901, 964],
       [500, 543, 645, 723, 823, 823]])

****In single dimension it will sort normally****

****In Multi dimension it will sorted using Axis****

****If we are not mentioned anything default it takes row wise axis****

In [ ]:
d = np.dtype([('name','S1'),('perc',float)])

In [ ]:
marks = np.array([("h",99.8),("l",98.3),("a",93.2)],dtype=d)

In [ ]:
marks

array([(b'h', 99.8), (b'l', 98.3), (b'a', 93.2)],
      dtype=[('name', 'S1'), ('perc', '<f8')])

In [ ]:
np.sort(marks,order="name")

array([(b'a', 93.2), (b'h', 99.8), (b'l', 98.3)],
      dtype=[('name', 'S1'), ('perc', '<f8')])

In [ ]:
np.sort(marks,order="perc")

array([(b'a', 93.2), (b'l', 98.3), (b'h', 99.8)],
      dtype=[('name', 'S1'), ('perc', '<f8')])

#**reshape**

In [ ]:
a = np.array([234,687,834,964,543,500,823,645,823,723])
a

array([234, 687, 834, 964, 543, 500, 823, 645, 823, 723])

In [ ]:
a.reshape(2,6)

ValueError: ignored

In [ ]:
a = np.arange(20,280,10)
a

array([ 20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120, 130, 140,
       150, 160, 170, 180, 190, 200, 210, 220, 230, 240, 250, 260, 270])

In [ ]:
a.reshape(2,8)

ValueError: ignored

In [ ]:
a.reshape(8,2)

In [ ]:
a.reshape(4,4)

In [ ]:
a.reshape(2,4,2)

In [ ]:
a.reshape(2,2,2)

ValueError: ignored

#**append()**

*append is applied between two arrays*

In [ ]:
a = np.array([234,387,465,834,964,201,543,500,823,645,833,923])
print(a)

[234 387 465 834 964 201 543 500 823 645 833 923]


In [ ]:
b = np.array([364,296,975,345,253,785,241,940,823,764,241,623])
print(b)

[364 296 975 345 253 785 241 940 823 764 241 623]


In [ ]:
np.append(a,b)

array([ 20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120, 130, 140,
       150, 160, 170, 180, 190, 200, 210, 220, 230, 240, 250, 260, 270,
       234, 387, 465, 834, 999, 201, 543, 500, 823, 645, 823, 923])

In [ ]:
a = np.array([[234,387,465,834,964,201],[543,500,823,645,833,923]])
print(a)

[[234 387 465 834 964 201]
 [543 500 823 645 833 923]]


#**insert()**


insert is also similar to append

insert is taken single dimension continous

memory location index array

In [ ]:
a=np.array([[123,456,365,345,789,345],[334,778,567,375,238,567]])
print(a)

[[123 456 365 345 789 345]
 [334 778 567 375 238 567]]


In [ ]:
np.insert(a,5,999)

array([123, 456, 365, 345, 789, 999, 345, 334, 778, 567, 375, 238, 567])

In [ ]:
np.insert(a,5,[999,345,333,567,133,124])

array([123, 456, 365, 345, 789, 999, 345, 333, 567, 133, 124, 345, 334,
       778, 567, 375, 238, 567])

#**inserting multuiple elements**



**result generated in single dimension only**

**Subscript[ ] is used for inserting multiple elements**

In [ ]:
np.insert(a,5,[999,345,333,567,133,124]).reshape(3,6)

array([[123, 456, 365, 345, 789, 999],
       [345, 333, 567, 133, 124, 345],
       [334, 778, 567, 375, 238, 567]])

In [ ]:
np.insert(a,5,[999,345,333,567,133,124]).reshape(3,3,2)

array([[[123, 456],
        [365, 345],
        [789, 999]],

       [[345, 333],
        [567, 133],
        [124, 345]],

       [[334, 778],
        [567, 375],
        [238, 567]]])

#**delete()**

In [ ]:
a=np.array([123,344,566,567,745,123,454,334,778,567,375,238,567])
print(a)

[123 344 566 567 745 123 454 334 778 567 375 238 567]


In [ ]:
np.delete(a,8)

array([123, 344, 566, 567, 745, 123, 454, 334, 567, 375, 238, 567])

In [ ]:
a=np.array([[123,456,365,345,789,345],[334,778,567,375,238,567]])
print(a)

[[123 456 365 345 789 345]
 [334 778 567 375 238 567]]


In [ ]:
np.delete(a,6)

array([123, 456, 365, 345, 789, 345, 778, 567, 375, 238, 567])

In [ ]:
np.delete(a,10)

array([123, 456, 365, 345, 789, 345, 334, 778, 567, 375, 567])

#**concatenate()**



two different arrays are conatenated

In [ ]:
a=np.array([123,344,566,567,745,123,454,334,778,567,375,238])
a

array([123, 344, 566, 567, 745, 123, 454, 334, 778, 567, 375, 238])

In [ ]:
b=np.array([123,344,566,345,567,745,334,778,567,375,238,567])
b

array([123, 344, 566, 345, 567, 745, 334, 778, 567, 375, 238, 567])

In [ ]:
np.concatenate((a,b)) #all elements will be in one dimension only

array([123, 344, 566, 567, 745, 123, 454, 334, 778, 567, 375, 238, 123,
       344, 566, 345, 567, 745, 334, 778, 567, 375, 238, 567])

In [ ]:
np.concatenate((a,b),axis=0) #row case concatination

array([123, 344, 566, 567, 745, 123, 454, 334, 778, 567, 375, 238, 123,
       344, 566, 345, 567, 745, 334, 778, 567, 375, 238, 567])

#**stack()**

In [ ]:
a=np.array([123,344,566,567,745,123,454,334,778,567,375,238])
print(a)

[123 344 566 567 745 123 454 334 778 567 375 238]


In [ ]:
b=np.array([123,344,566,345,567,745,334,778,567,375,238,567])
print(b)

[123 344 566 345 567 745 334 778 567 375 238 567]


In [ ]:
np.stack((a,b))  #stack seperates two arrays elements but concatenation not seperated the array elements

array([[123, 344, 566, 567, 745, 123, 454, 334, 778, 567, 375, 238],
       [123, 344, 566, 345, 567, 745, 334, 778, 567, 375, 238, 567]])

In [ ]:
res=np.stack((a,b))
res

array([[123, 344, 566, 567, 745, 123, 454, 334, 778, 567, 375, 238],
       [123, 344, 566, 345, 567, 745, 334, 778, 567, 375, 238, 567]])

In [ ]:
res[0]

array([123, 344, 566, 567, 745, 123, 454, 334, 778, 567, 375, 238])

In [ ]:
res[1]

array([123, 344, 566, 345, 567, 745, 334, 778, 567, 375, 238, 567])

In [ ]:
res1=np.concatenate((a,b))
res1

array([123, 344, 566, 567, 745, 123, 454, 334, 778, 567, 375, 238, 123,
       344, 566, 345, 567, 745, 334, 778, 567, 375, 238, 567])

In [ ]:
res1[9]

567

#**vstack()**

vertical stack

In [ ]:
a=np.array([[10,20],[30,40]])
a

array([[10, 20],
       [30, 40]])

In [ ]:
b=np.array([[50,60],[70,80]])
b

array([[50, 60],
       [70, 80]])

In [ ]:
np.vstack((a,b))

array([[10, 20],
       [30, 40],
       [50, 60],
       [70, 80]])

#**hstack()**

horizontal stack

In [ ]:
np.hstack((a,b)) #concatenation with respect to axis

array([[10, 20, 50, 60],
       [30, 40, 70, 80]])

In [ ]:
np.concatenate((a,b))

array([[10, 20],
       [30, 40],
       [50, 60],
       [70, 80]])

In [ ]:
np.concatenate((a,b),axis=1) #hstack

array([[10, 20, 50, 60],
       [30, 40, 70, 80]])

#**dstack()**

depth wise

In [ ]:
a=np.array([[10,20],[30,40]])
a

array([[10, 20],
       [30, 40]])

In [ ]:
b=np.array([[50,60],[70,80]])
b

array([[50, 60],
       [70, 80]])

In [ ]:
np.dstack((a,b))

array([[[10, 50],
        [20, 60]],

       [[30, 70],
        [40, 80]]])

#**split()**

In [ ]:
x=np.arange(5,60,2)
print(x)

[ 5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47 49 51
 53 55 57 59]


In [ ]:
np.split(x,7) #equal divisions

[array([ 5,  7,  9, 11]),
 array([13, 15, 17, 19]),
 array([21, 23, 25, 27]),
 array([29, 31, 33, 35]),
 array([37, 39, 41, 43]),
 array([45, 47, 49, 51]),
 array([53, 55, 57, 59])]

In [ ]:
np.split(x,2)

[array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31]),
 array([33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59])]

In [ ]:
np.split(x,14)

[array([5, 7]),
 array([ 9, 11]),
 array([13, 15]),
 array([17, 19]),
 array([21, 23]),
 array([25, 27]),
 array([29, 31]),
 array([33, 35]),
 array([37, 39]),
 array([41, 43]),
 array([45, 47]),
 array([49, 51]),
 array([53, 55]),
 array([57, 59])]

In [ ]:
np.split(x,7)

[array([ 5,  7,  9, 11]),
 array([13, 15, 17, 19]),
 array([21, 23, 25, 27]),
 array([29, 31, 33, 35]),
 array([37, 39, 41, 43]),
 array([45, 47, 49, 51]),
 array([53, 55, 57, 59])]

In [ ]:
z=np.split(x,7)
print(z)

[array([ 5,  7,  9, 11]), array([13, 15, 17, 19]), array([21, 23, 25, 27]), array([29, 31, 33, 35]), array([37, 39, 41, 43]), array([45, 47, 49, 51]), array([53, 55, 57, 59])]


In [ ]:
S1,S2,S3,S4,S5,S6,S7=np.split(x,7)
S1

array([ 5,  7,  9, 11])

In [ ]:
S2

array([13, 15, 17, 19])

In [ ]:
S3

array([21, 23, 25, 27])

In [ ]:
S4

array([29, 31, 33, 35])

In [ ]:
S5

array([37, 39, 41, 43])

In [ ]:
S6

array([45, 47, 49, 51])

In [ ]:
S7

array([53, 55, 57, 59])

#**where()**

it checks whether the elements are present in the array or not

In [ ]:
a

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45],
       [50, 55, 60]])

In [ ]:
a=np.arange(5,65,5).reshape(4,3)
a

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45],
       [50, 55, 60]])

In [ ]:
np.where(a==55)

(array([3]), array([1]))

In [ ]:
a=np.arange(5,65,5).reshape(6,2)
a

array([[ 5, 10],
       [15, 20],
       [25, 30],
       [35, 40],
       [45, 50],
       [55, 60]])

In [ ]:
np.where(a==40)

(array([3]), array([1]))

In [ ]:
b=np.arange(10,100,6)
b

array([10, 16, 22, 28, 34, 40, 46, 52, 58, 64, 70, 76, 82, 88, 94])

In [ ]:
np.where(b==52)

(array([7]),)

In [ ]:
a

array([[ 5, 10],
       [15, 20],
       [25, 30],
       [35, 40],
       [45, 50],
       [55, 60]])

In [ ]:
np.where(a%20==0)

(array([1, 3, 5]), array([1, 1, 1]))

#**searchsorted()**

In [ ]:
a=np.array([112,34,45,6,345,3,78,788,9])
a

array([112,  34,  45,   6, 345,   3,  78, 788,   9])

In [ ]:
b=np.searchsorted(a,112)
b

4

In [ ]:
np.searchsorted(a,34)

0

In [ ]:
np.searchsorted(a,3)

0

In [ ]:
np.searchsorted(a,78)

4

In [ ]:
np.searchsorted(a,345)

4

In [ ]:
np.searchsorted(a,788)

7

#**Aritrhmetic Operations**



add()

subtract()

multiply()

divide()

exp()

sqrt()

comparision()

##**add()**

In [ ]:
a=np.array([[12,45,34],[56,78,76]])
print(a)

[[12 45 34]
 [56 78 76]]


In [ ]:
b=np.array([[15,65,38],[46,70,95]])
print(b)

[[15 65 38]
 [46 70 95]]


In [ ]:
np.add(a,b)

array([[ 27, 110,  72],
       [102, 148, 171]])

In [ ]:
c=np.array([[34,45,22],[34,75,89]])
print(c)

[[34 45 22]
 [34 75 89]]


In [ ]:
np.add(b,c)

In [ ]:
np.add(a,c)

In [ ]:
np.add(a,b,b)

array([[ 27, 110,  72],
       [102, 148, 171]])

##**subtract()**

In [ ]:
np.subtract(a,b)

array([[-15, -65, -38],
       [-46, -70, -95]])

In [ ]:
np.subtract(b,a)

array([[15, 65, 38],
       [46, 70, 95]])

In [ ]:
np.subtract(a,b,c)

ValueError: ignored

##**multiply()**

In [ ]:
np.multiply(a,b)

array([[  324,  4950,  2448],
       [ 5712, 11544, 12996]])

In [ ]:
np.multiply(a,b,c)

ValueError: ignored

In [ ]:
np.multiply(b,c)

ValueError: ignored

##**divide()**

In [ ]:
np.divide(a,b)

array([[0.44444444, 0.40909091, 0.47222222],
       [0.54901961, 0.52702703, 0.44444444]])

In [ ]:
np.divide(b,c)

ValueError: ignored

In [ ]:
np.divide(a,c)

ValueError: ignored

##**exponential()**

In [ ]:
np.exp(a)

array([[1.62754791e+05, 3.49342711e+19, 5.83461743e+14],
       [2.09165950e+24, 7.49841700e+33, 1.01480039e+33]])

In [ ]:
np.exp(b)

array([[5.32048241e+11, 5.92097203e+47, 1.85867175e+31],
       [1.98626484e+44, 1.88618081e+64, 1.83804612e+74]])

In [ ]:
np.exp(c)

<ipython-input-152-57f1ac071346>:1: RuntimeWarning: overflow encountered in exp
  np.exp(c)


array([[4.21607925e+101, 1.18022415e+168, 8.84981282e+201,
                    inf,             inf, 1.96422332e+087],
       [6.63595868e+235, 1.40359222e+217,             inf,
        1.31807714e+280,             inf,             inf]])

##**sqrt()**

In [ ]:
np.sqrt(a)

array([[3.46410162, 6.70820393, 5.83095189],
       [7.48331477, 8.83176087, 8.71779789]])

In [ ]:
np.sqrt(b)

In [ ]:
np.sqrt(c)

##**Comparision**

"="is applied in comparision

In [ ]:
a

array([[12, 45, 34],
       [56, 78, 76]])

In [ ]:
b

array([[ 27, 110,  72],
       [102, 148, 171]])

In [ ]:
c

array([[  324,  4950,  2448],
       [ 5712, 11544, 12996]])

In [ ]:
b[1][0]

102

In [ ]:
b[1][1]

148

In [ ]:
np.array_equal(a,b)

False

In [ ]:
np.array_equal(b,c)

False

In [ ]:
np.array_equal(a,c)

False

#**ARRAY FUNCTIONS**


sum()

min()

max()

mean()

median()

var()

std()


In [ ]:
a = np.array([[100,200],[300,400],[500,600]])
a

array([[100, 200],
       [300, 400],
       [500, 600]])

##sum()

In [ ]:
np.sum(a)

2100

In [ ]:
np.sum(a,axis=1)

array([ 300,  700, 1100])

In [ ]:
np.sum(a,axis=0)

array([ 900, 1200])

##min()

In [ ]:
np.min(a)

100

In [ ]:
np.min(a,axis=1)

array([100, 300, 500])

In [ ]:
np.min(a,axis=0)

array([100, 200])

##max()

In [ ]:
np.max(a)

600

In [ ]:
np.max(a,axis=1)

array([200, 400, 600])

In [ ]:
np.max(a,axis=0)

array([500, 600])

##mean()

In [ ]:
np.mean(a)

350.0

In [ ]:
np.mean(a,axis=1)

array([150., 350., 550.])

In [ ]:
np.mean(a,axis=0)

array([300., 400.])

##median()

In [ ]:
np.median(a)

350.0

In [ ]:
np.median(a,axis=1)

array([150., 350., 550.])

In [ ]:
np.median(a,axis=0)

array([300., 400.])

##var()

***Variance***

In [ ]:
np.var(a)

29166.666666666668

In [ ]:
np.var(a,axis=1)

array([2500., 2500., 2500.])

In [ ]:
np.var(a,axis=1)

array([2500., 2500., 2500.])

##std()

***standard deviation***

In [ ]:
np.median(a,axis=1)

array([150., 350., 550.])

In [ ]:
np.median(a,axis=1)

array([150., 350., 550.])

In [ ]:
np.median(a,axis=1)

array([150., 350., 550.])